name = "Forged Extraction"
author = "oygurd"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4343de1639f5c5cc0099f69cf86f992f844ea078a8a31047ba6414f01fb5e5f1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
