name = "Forged Extraction"
author = "oygurd"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea0c97adaed86f4c47b3a9456b5053a6a29ffd3e732db83fdf471c05420ecea7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
