name = "create focused war"
author = "oygurd"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0d8e1cba1847c6ed4ae8d09a6b058a2fec8603ab533e670affb213404c1ad8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
